apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task-api-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: task-api
  namespaceSelector:
    matchNames:
      - task-management
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
